[package]
name = "spqr-shortest-path-index"
description = "A shortest-path index for bidirected graphs based on the SPQR decomposition."
version = "0.2.3"
authors = ["Sebastian Schmidt <sebastian.schmidt@helsinki.fi>"]
license = "BSD-2-Clause"
repository = "https://github.com/sebschmi/spqr-shortest-path-index"

edition = "2024"

[features]
binary-io = [
    "spqr-tree/binary-io",
    "bidirected-adjacency-array/binary-io",
    "tagged-vec/binary-io",
]

[dependencies]
spqr-tree = { version = "1.0.0", features = ["bidirected-adjacency-array"] }
bidirected-adjacency-array = { version = "0.3.1" }
optional-numeric-index = "0.4.0"
num-traits = "0.2.19"
binary-heap-plus = "0.5.0"
tagged-vec = "0.4.6"
bitvec = "1.0.1"
epoch-reset-array = "0.1.0"
